### ISSUE TITLE
Microtasks?

### ISSUE THREAD

**Issue by chrisvasz** [getify/native-promise-only#53]
I might be covering ground that has already been covered here, but it appears that NPO executes promises on a macrotask queue instead of a microtask queue. I am looking [here](https://github.com/getify/native-promise-only/blob/519d1cddb1128e3c51e93f5f4ec03460c42b51e9/lib/npo.src.js#L17) specifically.

When I run this code in Chrome,

``` js
require('setimmediate');  // runs on the macrotask queue
setImmediate(() => console.log('immediate'));
Promise.resolve().then(() => console.log('promise'));
```

I get the following output (expected):

```
promise
immediate
```

When I run the following code,

``` js
require('setimmediate');  // runs on the macrotask queue
delete global.Promise;
require('native-promise-only');
setImmediate(() => console.log('immediate'));
Promise.resolve().then(() => console.log('promise'));
```

the output looks like this instead:

```
immediate
promise
```

Admittedly, the spec isn't clear about macrotasks vs microtasks, but it seems that the consensus among vendors is that promises run as microtasks. [Here is a Firefox ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1193394) to run Promise callbacks as microtasks. Bluebird schedules Promise callbacks as microtasks -- [here is a relevant discussion](https://github.com/nodejs/node/issues/2736#issuecomment-138614266).

**Comment by getify** [comment]
Yes, you are correct, though I believe the terms (microtask, macrotask) are not fully agreed on here.

For async scheduling, NPO chooses to use `setImmediate(..)` if available, `setTimeout(..0)` otherwise. There exist several hacky ways of simulating microtask scheduling using mutation observers and other such things, but the weight of these tricks would double the size of this polyfill.

Furthermore, it is generally considered a bad practice to rely on the relative ordering of promise tasks with other async tasks. So, I don't think the "cost" of supporting something slightly more strictly adhering to the spirit of the spec is worth it in such a case. That's why NPO takes the simpler/smaller approach.
